using FluentAssertions;
using SampleApp.Auth;
using SampleApp.Pricing;

namespace SampleApp.Tests;

/// <summary>
/// Regression and boundary tests generated by the unit-test-generator agent
/// for the three fixes described in context/bugs/001/fix-summary.md.
///
/// Coverage map:
///   Fix 1 (off-by-one >= 10)          → GetDiscountRate_* tests
///   Fix 2 (tax on discounted subtotal) → CalculateTotal_WithDiscount_* tests
///   Fix 3 (env-var token + const-time) → IsAdmin_* tests
/// </summary>
public class Bug001RegressionTests
{
    // =========================================================================
    // Fix 1 — GetDiscountRate: off-by-one boundary (> 10 → >= 10)
    // =========================================================================

    /// <summary>
    /// Regression test for Fix 1.
    /// With the old code (> 10) exactly 10 units returned 0m. The fix uses >= 10.
    /// </summary>
    [Fact]
    public void GetDiscountRate_ExactlyAtThreshold_ReturnsTenPercent()
    {
        decimal rate = OrderCalculator.GetDiscountRate(10);

        rate.Should().Be(0.10m);
    }

    /// <summary>
    /// Lower boundary neighbour: 9 units must never earn the discount.
    /// Ensures the >= boundary is correct on the low side.
    /// </summary>
    [Fact]
    public void GetDiscountRate_OneBelowThreshold_ReturnsZero()
    {
        decimal rate = OrderCalculator.GetDiscountRate(9);

        rate.Should().Be(0m);
    }

    /// <summary>
    /// Edge input: zero units must not trigger a discount.
    /// </summary>
    [Fact]
    public void GetDiscountRate_ZeroQuantity_ReturnsZero()
    {
        decimal rate = OrderCalculator.GetDiscountRate(0);

        rate.Should().Be(0m);
    }

    // =========================================================================
    // Fix 2 — CalculateTotal: tax must be applied to the discounted subtotal
    // =========================================================================

    /// <summary>
    /// Regression test for Fix 2.
    /// qty=20 @ $100 each: subtotal=2000, discounted=1800, total=1944.00.
    /// With the old bug (tax on pre-discount subtotal) the result was 1960.00.
    /// </summary>
    [Fact]
    public void CalculateTotal_WithDiscount_AppliesTaxToDiscountedSubtotal()
    {
        OrderItem item = new("BulkWidget", 100m, 20);

        decimal total = OrderCalculator.CalculateTotal(item);

        total.Should().Be(1944.00m);
    }

    /// <summary>
    /// Boundary combo test (Fix 1 + Fix 2 together).
    /// qty=10 @ $50 each: subtotal=500, discounted=450, total=486.00.
    /// Verifies both the >= boundary and the correct tax order.
    /// </summary>
    [Fact]
    public void CalculateTotal_ExactlyAtDiscountBoundary_AppliesBothDiscountAndTaxCorrectly()
    {
        OrderItem item = new("BoundaryWidget", 50m, 10);

        decimal total = OrderCalculator.CalculateTotal(item);

        total.Should().Be(486.00m); // 500 * 0.90 * 1.08
    }

    // =========================================================================
    // Fix 3 — TokenAuthenticator: env-var token + constant-time comparison
    //
    // FIRST / R note: TokenAuthenticator.IsAdmin reads from the real
    // Environment.GetEnvironmentVariable, which is non-deterministic across
    // machines. Each test below saves the current value, sets the value it
    // needs, then restores the original in a finally block, making the tests
    // deterministic regardless of the ambient environment.
    //
    // Seam gap: there is no injection point for the env-var lookup; the minimal
    // refactor that would fully satisfy FIRST without save/restore is to add a
    // Func<string, string?> parameter defaulting to Environment.GetEnvironmentVariable.
    // This is recorded as a testability gap in test-report.md — no production code
    // is changed here.
    // =========================================================================

    /// <summary>
    /// Null input must be rejected before any env-var lookup (fast early exit).
    /// </summary>
    [Fact]
    public void IsAdmin_NullToken_ReturnsFalse()
    {
        bool result = TokenAuthenticator.IsAdmin(null!);

        result.Should().BeFalse();
    }

    /// <summary>
    /// Empty-string input must be rejected before any env-var lookup.
    /// </summary>
    [Fact]
    public void IsAdmin_EmptyToken_ReturnsFalse()
    {
        bool result = TokenAuthenticator.IsAdmin(string.Empty);

        result.Should().BeFalse();
    }

    /// <summary>
    /// When ADMIN_TOKEN is absent the method must return false even for a non-empty token.
    /// Saves and nulls the env var so this test is independent of other tests that set it.
    /// </summary>
    [Fact]
    public void IsAdmin_MissingEnvVar_ReturnsFalse()
    {
        string? saved = Environment.GetEnvironmentVariable("ADMIN_TOKEN");
        Environment.SetEnvironmentVariable("ADMIN_TOKEN", null);
        try
        {
            bool result = TokenAuthenticator.IsAdmin("any-non-empty-token");

            result.Should().BeFalse();
        }
        finally
        {
            // Restore so other tests that rely on a preset value are not broken.
            Environment.SetEnvironmentVariable("ADMIN_TOKEN", saved);
        }
    }

    /// <summary>
    /// Happy path for Fix 3: when ADMIN_TOKEN matches the supplied token IsAdmin returns true.
    /// Uses a unique test-local token value to avoid coupling with other tests.
    /// </summary>
    [Fact]
    public void IsAdmin_CorrectTokenWithEnvVarSet_ReturnsTrue()
    {
        const string testToken = "bug001-test-token-correct";
        string? saved = Environment.GetEnvironmentVariable("ADMIN_TOKEN");
        Environment.SetEnvironmentVariable("ADMIN_TOKEN", testToken);
        try
        {
            bool result = TokenAuthenticator.IsAdmin(testToken);

            result.Should().BeTrue();
        }
        finally
        {
            Environment.SetEnvironmentVariable("ADMIN_TOKEN", saved);
        }
    }

    /// <summary>
    /// Negative path with env var present.
    /// Tests the CryptographicOperations.FixedTimeEquals code path (not the missing-env-var guard).
    /// The old code used string == which was also a security issue; this exercises the new path.
    /// </summary>
    [Fact]
    public void IsAdmin_WrongTokenWithEnvVarSet_ReturnsFalse()
    {
        const string testToken = "bug001-test-token-correct";
        string? saved = Environment.GetEnvironmentVariable("ADMIN_TOKEN");
        Environment.SetEnvironmentVariable("ADMIN_TOKEN", testToken);
        try
        {
            bool result = TokenAuthenticator.IsAdmin("definitely-wrong-token");

            result.Should().BeFalse();
        }
        finally
        {
            Environment.SetEnvironmentVariable("ADMIN_TOKEN", saved);
        }
    }
}
